### ISSUE TITLE
Suggestions/Todo

### ISSUE THREAD

**Issue by PiggyPiglet** [help-chat/Gary#2]
- [x] Suggestion command
- [x] Ban check for helpful
- [ ] auto cleaning of request and offer services
- [ ] auto detect errors and hastebin
- [ ] Canned Responses
- [x] Clean up file related code to follow DRY principles

**Comment by Andre601** [comment]
[] Canned responses.

**Comment by CraftingBro** [comment]
AI is not self aware

**Comment by Andre601** [comment]
* Command for Help Chat-Helpers, to delete messages of users (eg. because of Advertisement)
* Warn-System. Something like a Strike-Style system. 3 Warnings = punishment.

**Comment by lewis2470** [comment]
paginate placeholders

**Comment by darbyjack** [comment]
Please sync add the reactions to RMS so that they will be in order.

**Comment by Andre601** [comment]
> Please sync add the reactions to RMS so that they will be in order.

How can we understand that?

**Comment by Andre601** [comment]
Also, Discord itself (the client more exactly) will often mix up order since it won't load all reactions in order... Some take longer than others.
So, in conclusion, would this be a minor "fix"

**Comment by PiggyPiglet** [comment]
Yeah, discord re-orders reactions on client reload, so this fix wouldn’t work.
